name: visakeeper
description: A new Flutter project.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  json_annotation:
  intl:
  cloud_firestore: ^0.4.0
  firebase_auth: "^0.5.5"
  google_sign_in: "^3.0.2"

dev_dependencies: 
  flutter_test:
    sdk: flutter
  build_runner: 
  json_serializable:

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/email.png
    - assets/flags/ad.png
    - assets/flags/ae.png
    - assets/flags/af.png
    - assets/flags/ag.png
    - assets/flags/ai.png
    - assets/flags/al.png
    - assets/flags/am.png
    - assets/flags/ao.png
    - assets/flags/aq.png
    - assets/flags/ar.png
    - assets/flags/as.png
    - assets/flags/at.png
    - assets/flags/au.png
    - assets/flags/aw.png
    - assets/flags/ax.png
    - assets/flags/az.png
    - assets/flags/ba.png
    - assets/flags/bb.png
    - assets/flags/bd.png
    - assets/flags/be.png
    - assets/flags/bf.png
    - assets/flags/bg.png
    - assets/flags/bh.png
    - assets/flags/bi.png
    - assets/flags/bj.png
    - assets/flags/bl.png
    - assets/flags/bm.png
    - assets/flags/bn.png
    - assets/flags/bo.png
    - assets/flags/bq.png
    - assets/flags/br.png
    - assets/flags/bs.png
    - assets/flags/bt.png
    - assets/flags/bv.png
    - assets/flags/bw.png
    - assets/flags/by.png
    - assets/flags/bz.png
    - assets/flags/ca.png
    - assets/flags/cc.png
    - assets/flags/cd.png
    - assets/flags/cf.png
    - assets/flags/cg.png
    - assets/flags/ch.png
    - assets/flags/ci.png
    - assets/flags/ck.png
    - assets/flags/cl.png
    - assets/flags/cm.png
    - assets/flags/cn.png
    - assets/flags/co.png
    - assets/flags/cr.png
    - assets/flags/cu.png
    - assets/flags/cv.png
    - assets/flags/cw.png
    - assets/flags/cx.png
    - assets/flags/cy.png
    - assets/flags/cz.png
    - assets/flags/de.png
    - assets/flags/dj.png
    - assets/flags/dk.png
    - assets/flags/dm.png
    - assets/flags/do.png
    - assets/flags/dz.png
    - assets/flags/ec.png
    - assets/flags/ee.png
    - assets/flags/eg.png
    - assets/flags/eh.png
    - assets/flags/er.png
    - assets/flags/es.png
    - assets/flags/et.png
    - assets/flags/fi.png
    - assets/flags/fj.png
    - assets/flags/fk.png
    - assets/flags/fm.png
    - assets/flags/fo.png
    - assets/flags/fr.png
    - assets/flags/ga.png
    - assets/flags/gb-eng.png
    - assets/flags/gb-nir.png
    - assets/flags/gb-sct.png
    - assets/flags/gb-wls.png
    - assets/flags/gb.png
    - assets/flags/gd.png
    - assets/flags/ge.png
    - assets/flags/gf.png
    - assets/flags/gg.png
    - assets/flags/gh.png
    - assets/flags/gi.png
    - assets/flags/gl.png
    - assets/flags/gm.png
    - assets/flags/gn.png
    - assets/flags/gp.png
    - assets/flags/gq.png
    - assets/flags/gr.png
    - assets/flags/gs.png
    - assets/flags/gt.png
    - assets/flags/gu.png
    - assets/flags/gw.png
    - assets/flags/gy.png
    - assets/flags/hk.png
    - assets/flags/hm.png
    - assets/flags/hn.png
    - assets/flags/hr.png
    - assets/flags/ht.png
    - assets/flags/hu.png
    - assets/flags/id.png
    - assets/flags/ie.png
    - assets/flags/il.png
    - assets/flags/im.png
    - assets/flags/in.png
    - assets/flags/io.png
    - assets/flags/iq.png
    - assets/flags/ir.png
    - assets/flags/is.png
    - assets/flags/it.png
    - assets/flags/je.png
    - assets/flags/jm.png
    - assets/flags/jo.png
    - assets/flags/jp.png
    - assets/flags/ke.png
    - assets/flags/kg.png
    - assets/flags/kh.png
    - assets/flags/ki.png
    - assets/flags/km.png
    - assets/flags/kn.png
    - assets/flags/kp.png
    - assets/flags/kr.png
    - assets/flags/kw.png
    - assets/flags/ky.png
    - assets/flags/kz.png
    - assets/flags/la.png
    - assets/flags/lb.png
    - assets/flags/lc.png
    - assets/flags/li.png
    - assets/flags/lk.png
    - assets/flags/lr.png
    - assets/flags/ls.png
    - assets/flags/lt.png
    - assets/flags/lu.png
    - assets/flags/lv.png
    - assets/flags/ly.png
    - assets/flags/ma.png
    - assets/flags/mc.png
    - assets/flags/md.png
    - assets/flags/me.png
    - assets/flags/mf.png
    - assets/flags/mg.png
    - assets/flags/mh.png
    - assets/flags/mk.png
    - assets/flags/ml.png
    - assets/flags/mm.png
    - assets/flags/mn.png
    - assets/flags/mo.png
    - assets/flags/mp.png
    - assets/flags/mq.png
    - assets/flags/mr.png
    - assets/flags/ms.png
    - assets/flags/mt.png
    - assets/flags/mu.png
    - assets/flags/mv.png
    - assets/flags/mw.png
    - assets/flags/mx.png
    - assets/flags/my.png
    - assets/flags/mz.png
    - assets/flags/na.png
    - assets/flags/nc.png
    - assets/flags/ne.png
    - assets/flags/nf.png
    - assets/flags/ng.png
    - assets/flags/ni.png
    - assets/flags/nl.png
    - assets/flags/no.png
    - assets/flags/np.png
    - assets/flags/nr.png
    - assets/flags/nu.png
    - assets/flags/nz.png
    - assets/flags/om.png
    - assets/flags/pa.png
    - assets/flags/pe.png
    - assets/flags/pf.png
    - assets/flags/pg.png
    - assets/flags/ph.png
    - assets/flags/pk.png
    - assets/flags/pl.png
    - assets/flags/pm.png
    - assets/flags/pn.png
    - assets/flags/pr.png
    - assets/flags/ps.png
    - assets/flags/pt.png
    - assets/flags/pw.png
    - assets/flags/py.png
    - assets/flags/qa.png
    - assets/flags/re.png
    - assets/flags/ro.png
    - assets/flags/rs.png
    - assets/flags/ru.png
    - assets/flags/rw.png
    - assets/flags/sa.png
    - assets/flags/sb.png
    - assets/flags/sc.png
    - assets/flags/sd.png
    - assets/flags/se.png
    - assets/flags/sg.png
    - assets/flags/sh.png
    - assets/flags/si.png
    - assets/flags/sj.png
    - assets/flags/sk.png
    - assets/flags/sl.png
    - assets/flags/sm.png
    - assets/flags/sn.png
    - assets/flags/so.png
    - assets/flags/sr.png
    - assets/flags/ss.png
    - assets/flags/st.png
    - assets/flags/sv.png
    - assets/flags/sx.png
    - assets/flags/sy.png
    - assets/flags/sz.png
    - assets/flags/tc.png
    - assets/flags/td.png
    - assets/flags/tf.png
    - assets/flags/tg.png
    - assets/flags/th.png
    - assets/flags/tj.png
    - assets/flags/tk.png
    - assets/flags/tl.png
    - assets/flags/tm.png
    - assets/flags/tn.png
    - assets/flags/to.png
    - assets/flags/tr.png
    - assets/flags/tt.png
    - assets/flags/tv.png
    - assets/flags/tw.png
    - assets/flags/tz.png
    - assets/flags/ua.png
    - assets/flags/ug.png
    - assets/flags/um.png
    - assets/flags/us.png
    - assets/flags/uy.png
    - assets/flags/uz.png
    - assets/flags/va.png
    - assets/flags/vc.png
    - assets/flags/ve.png
    - assets/flags/vg.png
    - assets/flags/vi.png
    - assets/flags/vn.png
    - assets/flags/vu.png
    - assets/flags/wf.png
    - assets/flags/ws.png
    - assets/flags/xk.png
    - assets/flags/ye.png
    - assets/flags/yt.png
    - assets/flags/za.png
    - assets/flags/zm.png
    - assets/flags/zw.png
    - assets/countriesList.json
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages
